### ISSUE TITLE
Additional usernames to reserve

### ISSUE THREAD

**Issue by davidwagner** [kwappa/username_not_reserved_validator#3]
You might want to add the following users to your list of reserved usernames: ‘administrator’, ‘webmaster’, ‘hostmaster’, or ‘postmaster’.

Those 4 usernames are currently not included in username_not_reserved_validator/lib/username_not_reserved_validator/reserved_names.rb.  However, they are trusted by CA's: certificate authorities assume that anyone who controls any of those email addresses controls the entire domain, and will allow the owner of those email addresses to obtain a certificate for the domain.  For more information see http://security.stackexchange.com/q/84127.  Consequently, failing to reserve those usernames can cause security issues for domains that use SSL.

**Comment by kwappa** [comment]
:tada: thank you for your information!
added these names at https://github.com/kwappa/username_not_reserved_validator/pull/4
